# basics
title: Kotlin Resources
email: hello@kotlinresources.com
description: >
  Kotlin dev resources

url: 'https://www.kotlinresources.com'
baseurl: ''

twitter_username: kotlinresources
github_username: kotlinresources

# owner
owner:
  name: Kotlin Resources by Makery
  avatar: bio-photo.jpg
  email: hello@kotlinresources.com
  disqus-shortname:
  twitter: #username
  facebook: #username
  github: #username
  stackexchange: #http://stackoverflow.com/users/123456/username
  linkedin: #username
  instagram: #username
  flickr: #username
  tumblr: #username
  pinterest: #username
  weibo: #userid
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:

# settings
timezone: Europe/Budapest
future: false

permalink: '/:title'
paginate: 2

reading_time: true
words_per_minute: 200

# markdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
      css_class: 'highlight' 
      span:
        line_numbers: false
      block:
        line_numbers: true
        start_line: 1
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

# seo
webmaster_verifications:
  google: 1234
  bing: 1234
  alexa: 1234
  yandex: 1234

# algolia
algolia: 
  index_name: 'kotlinresources'
  excluded_files:
    - index.html
  settings:
    distinct: true
    attributesToIndex:
      - title
      - categories
      - url
      - tags
      - tagline
      - author

# build
gems:
  - algoliasearch-jekyll
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
