# Site settings
title: Kotlin Resources
email: hello@makery.co
description: Ultimate Resources for Kotlin language
url: "https://kotlinresources.com"
baseurl: ""
twitter:
  username: HelloKotlin

# Reading time settings
reading_time:     true
words_per_minute: 200

# include _Pages
include: ["_pages"]
exclude:
  - resources
  - Gemfile
  - Gemfile.lock
  - scripts

defaults:
  - scope:
      path: ""
    values:
      image: assets/kotlin-resources-fb-share.png


# Permalink settings
permalink: /:categories/:title/
relative_permalinks: false

# Gems
gems:
  - algoliasearch-jekyll
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-archives
  - jekyll-paginate
  - jekyll-gist

# Owner/author information
# Social networking links used in footer. Update and remove as you like.
# google plus id, include the '+', eg +mmistakes
author:
  name:
  avatar:
  bio:            "We're passionate about Kotlin."
  email:          hello@makery.co
  twitter:
  facebook:       wearemakery
  github:         kotlinresources
  linkedin:       makerco
  instagram:      wearemakery
  google_plus:

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Europe/Budapest
future:      false  # publish future dated posts --  true, false (default)

# Amount of post to show on home page
paginate: 100

# Syntax settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
      # Rouge Options â€º https://github.com/jneen/rouge#full-options
      css_class: 'highlight'
      #line_numbers: true # bad idea, spans don't need linenos and would inherit this option
      span:
        line_numbers: false
      block:
        line_numbers: false
        start_line: 1
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: true

# Archives settings
jekyll-archives:
  enabled: [categories, tags]
  layout: 'archive'
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/category/:name/'

# SEO settings
webmaster_verifications:
#  google: UA-62927326-5
#  bing: 1234
#  alexa: 1234
#  yandex: 1234

# Algolia settings
algolia:
  index_name: 'kotlinresources'
  excluded_files:
    - index.html
  settings:
    distinct: true
    attributesToIndex:
      - title
      - description
      - categories
      - url
      - tags
      - tagline
      - author
